CREATE TABLE association(id_asso INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
				   		 log_asso VARCHAR(50) NOT NULL,
				   		 pwd_asso VARCHAR(100) NOT NULL,
				   		 crea_cpt_asso TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				   		 adr_asso VARCHAR(100),
				   		 cplt_adr_asso VARCHAR(50),
				   		 cp_asso INT(5),
				   		 ville_asso VARCHAR(50),
				   		 mail_asso VARCHAR(50) NOT NULL,
				   		 tel_asso INT(8),
				   		 tel_sec_asso INT(8),
				   		 descr_asso VARCHAR(500),
				   		 logo_asso BLOB,
				   		 fb_asso VARCHAR(100),
				   		 twt_asso VARCHAR(100),
				   		 link_asso VARCHAR(100),
				   		 id_theme INT NOT NULL,
						 CONSTRAINT fk_assoTheme FOREIGN KEY(id_theme) REFERENCES theme(id_theme));