CREATE TABLE com(id_com INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
				 lib_com VARCHAR(500) NOT NULL,
				 date_com TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
				 origin_com VARCHAR(100),
				 id_news INT NOT NULL,
				 CONSTRAINT fk_comNews FOREIGN KEY(id_news) REFERENCES news(id_news));